### PR TITLE
Remove random addresses from generated stub

### PR DESCRIPTION
**Pull request by virtuald**

### CODE REVIEW

**Comment by sizmailov** [comment]
Thanks for PR! 

The default representation is not really informative and removing address would make it _completely_ useless. I think it would be meaningful to delete whole trailing comment for types with default default `repr()` representation (e.g. `foo: module.Foo # value = <module.Foo at 0xdeadbeaf>` would become `foo: module.Foo`)

Do you mind adding a couple of test for that?

**Comment by virtuald** [comment]
I thought about that, but felt it would annoying to deal with cases of lists `[<foo.Foo object at 0x1234>, ... ]` and other potentially embedded attr. My primary goal is to ensure that the output is deterministic, and this seemed to be the simplest way to accomplish that. I don't mind the extra `# value =` as it's consistent in noting that 'something' is there.

**Comment by virtuald** [comment]
Added tests.

**Comment by sizmailov** [comment]
I'm still inclined to remove `# value = <Foo object>` comments and keep it for anything more complex.

Note that there is another place where `repr()` results appear. It's default argument values (this time pybind11 calls repr, not stubgen). Probably it should be processed same way (not necessarily in this PR).

In tests `__all__` variable needs to be updated [too](https://travis-ci.com/github/sizmailov/pybind11-stubgen/builds/178142745#L814-L818)

**Comment by virtuald** [comment]
Ok, I adjusted it as you mentioned.

**Comment by sizmailov** [comment]
Thanks, merged!

**Pull request merged**
