### PR TITLE
feat: ✨ numpy-array-use-type-var flag

### LINKED ISSUE #187: Option to use TypeVars for numpy.ndarray's shape type argument
Type expressions like `numpy.ndarray[numpy.float32[4, n]]` (see also  #155) is not valid according to [`numpy.ndarray`'s type stubs](https://github.com/numpy/numpy/blob/605e34577affa99fd49bbb6156843953b81d92b8/numpy/__init__.pyi#L1424). It expects 2 type arguments, a shape and a dtype. While #113 and #115 have suggested that we use `numpy.typing.NDArray`, [it is just a type alias that provides no shape information](https://github.com/numpy/numpy/blob/907ccc3467006df46a95ef63f08c7ca546ff2c49/numpy/_typing/_array_like.py#L32), which we do have.

I would like to propose a new numpy stub generation flag that formats the `pybind11` style:

```python
numpy.ndarray[numpy.float32[m, 1]]
```

instead as:

```python

M = typing.TypeVar("M")
...  # any others

numpy.ndarray[tuple[M, typing_extensions.Literal[1]], numpy.dtype[numpy.float32]]
```

This would allow us to create stubs that support shape checking like this:

```python
from __future__ import annotations

from typing import TypeVar

import numpy as np
from typing_extensions import Literal

M = TypeVar("M")
N = TypeVar("N")
P = TypeVar("P")

def matmul(
    l: np.ndarray[tuple[M, N], np.dtype[np.float64]],
    r: np.ndarray[tuple[N, P], np.dtype[np.float64]],
) -> np.ndarray[tuple[M, P], np.dtype[np.float64]]:
    return l @ r

arr1: np.ndarray[tuple[Literal[2], Literal[3]], np.dtype[np.float64]] = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
arr2: np.ndarray[tuple[Literal[3], Literal[4]], np.dtype[np.float64]] = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=np.float64)

arr3 = matmul(arr1, arr2)  # pyright reveals the type is: ndarray[tuple[Literal[2], Literal[4]], dtype[float64]]
arr3.shape  # (2, 4)
```

### PR DESCRIPTION
**Pull request by ringohoffman**
Fixes #187

Adds the flag `--numpy-array-use-type-var` which reformats the `pybind11`-generated `numpy.ndarray[numpy.float32[m, 1]]` annotation as `numpy.ndarray[tuple[M, Literal[1]], numpy.dtype[numpy.float32]]` using `TypeVar`s; this allows for type-checker supported shape checking

Notable changes are:
* The addition of `FixNumpyArrayDimTypeVar`, corresponding to the `--numpy-array-use-type-var` flag
* `TypeVar_` struct (appended `_` to avoid conflicting with `from typing import TypeVar`), and new `Module.type_vars` field
* [`FixTypingTypeNames.parse_annotation_str()`](https://github.com/sizmailov/pybind11-stubgen/compare/master...ringohoffman:numpy-shape-typevar?expand=1#diff-289d00b72d59bc6abd440cae1271bd3457346ab85a6b53b34c060f26662e482bR372-R386) was extracted into a helper method so that it could be additionally be called on every item of `result.parameters` in order to expand the `Literal` inside the `result.parameters` into e.g.  `typing_extensions.Literal`
* `FixScipyTypeArguments` was added to remove type arguments from anything from `scipy.sparse`, since they are not generic and do not accept any type arguments; the shape annotations provided by `--numpy-array-wrap-with-annotated` are left intact
* `FixNumpyDtype` forces `numpy.dtype` without `parameters` to be `numpy.dtype[typing.Any]` since it expects one type argument

### CODE REVIEW

**Comment by ringohoffman** [comment]
Let me know what you want to do in the way of testing this. Does it make sense to create another set of sub-folders under each of `tests/stubs/python-*/pybind11-master`? 

* `tests/stubs/python-3.7/pybind11-master/numpy-array-wrap-with-annotated`
* `tests/stubs/python-3.7/pybind11-master/numpy-array-use-type-var`

?

Would we loop over these flags in `tests/check-demo-stubs-generation.sh`?

**Comment by sizmailov** [comment]
>  Does it make sense to create another set of sub-folders under each of `tests/stubs/python-*/pybind11-master`?
> 
>     * `tests/stubs/python-3.7/pybind11-master/numpy-array-wrap-with-annotated`
> 
>     * `tests/stubs/python-3.7/pybind11-master/numpy-array-use-type-var`
> 

Unfortunately yes. Let's limit the tests for `numpy-array-use-type-var` to the latest pybind11 and python.

> Would we loop over these flags in `tests/check-demo-stubs-generation.sh`?

No, let's add an extra command line option to `check-demo-stubs-generation.sh` for the numpy array transformation.
Let's create a separate entry for `numpy-array-use-type-var` in gh-actions yml.

**Comment by ringohoffman** [comment]
I gave it my best effort! Please let me know what you would have me change!

**Comment by sizmailov** [comment]
Thanks! Looks good to me!

The last minor thing. Let's make the CI job name for `numpy-array-use-type-var` different from the default one.

**Comment by sizmailov** [comment]
Many thanks for contribution. I'll publish it as `v2.4`

**Comment by ringohoffman** [comment]
Does this affect the status of #113 or #115?

**Comment by sizmailov** [comment]
Indeed, #115 could be closed.
I think #113 is not affected, since `nptyping` uses its own types.

**Pull request merged**
