### PR TITLE
Missing __module__ fix

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Great tool. I had some issues running it on a large module (https://github.com/CadQuery/OCP). Here is the workaround.

### CODE REVIEW

**Comment by sizmailov** [comment]
Thanks for report & PR! Change is small and apparently harmless to merge right away. 

Can you give a little bit more context why `__module__` is missing? Is it artifact of binding code or it can appear in regular python code too?

**Comment by adam-urbanczyk** [comment]
It chokes on the `mro` method that seems to be added automatically by pybind11. This happens for classes that represent exceptions. Regular classes get the `mro` method too but in that case `__module__` is defined.

To be honest I'm not sure that this is legal situation (will ask on pybind11), but I think it is quite handy to have that workaround.

**Comment by adam-urbanczyk** [comment]
Small correction: if I import the module in regular python console the class in question does seem to have `mro.__module__`. I'm afraid I cannot debug this any further. If you want to test yourself:
```
conda install -c cadquery -c conda-forge ocp
pybind11-stubgen OCP.TopoDS
```

**Comment by sizmailov** [comment]
Ok, thanks for details. I don't mind to have workarounds, just wanted to know if anything can be done beyond that.

**Pull request merged**
